### PR TITLE
add create buttons directory with create bass tab and create guitar t…

### PR DESCRIPTION
**Pull request by timcrisp94**
Add Create Buttons directory to Sidebar components directory
-add CreateGuitarTabButton and CreateBassTabButton directories with js and test files for each
-stub up js for both buttons

Both buttons display on sidebar and navigate to '/new'

Need to style buttons to match sidebar content. Also need to remove Latest and Trending buttons from sidebar, and remove create button from header.

### CODE REVIEW

**Review by dcollis92 — COMMENTED** [review]
nice! just need to adjust to pass tests

**Review by dcollis92 — DISMISSED** [review]

**Comment by timcrisp94** [comment]
Remove test files from guitar and bass directories

**Comment by timcrisp94** [comment]
Remove unused variables from create guitar and bass tab files

**Review by RyanSUP — COMMENTED** [review]
Ah yea. Test files need at least 1 test. Todos work though! Another option would be to stub up some tests you would like to do:

`test.todo('write a test description')`

**Comment by timcrisp94** [comment]
-handled test error, which wasn't really an error, just snapshot
-created new routes for new guitar and bass tabs, added numberOfStrings props

**Comment by timcrisp94** [comment]
clean up pseudo

**Review by dcollis92 — COMMENTED** [review]
Passed all checks! Looks great!!

**Review by dcollis92 — APPROVED** [review]

**Pull request merged**
